services:
  web-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine3.21
    hostname: database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine3.20

  celery-worker:
    build: .
    hostname: worker-1
    command: celery -A src worker --loglevel=info
    volumes:
      - ./src/:/app/src/
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

volumes:
  data: