services:
  web-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./src:/usr/app/src/
      - ./tests:/usr/app/tests/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    hostname: database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0

  celery-worker:
    build: .
    hostname: worker-1
    command: celery -A src.core worker --loglevel=info
    volumes:
      - ./src:/usr/app/src/
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  data: