services:
  db:
    image: postgres:16
    container_name: uweather-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"

volumes:
  data: