services:
  web-app:
    build: .
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app/
      - static:/app/src/staticfiles
    expose:
      - 8000
    depends_on:
      - db
      - redis

  nginx:
    build: ./docker/nginx-conf
    volumes:
      - ./nginx-conf/:/etc/nginx/conf.d/
      - static_vol:/app/src/staticfiles
    ports:
      - "81:80"
    depends_on:
      - web-app

  db:
    image: postgres:16-alpine3.21
    hostname: database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine3.20

  celery-worker:
    build: .
    hostname: worker-1
    command: celery -A src worker --loglevel=info
    volumes:
      - ./src/:/app/src/
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  data:
  static: